#apiVersion: v1
#kind: Namespace
#metadata:
#  name: nginxns
#---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/sounakpatra/github-demo.git
    targetRevision: HEAD
    path: nginx
    kustomize:
      namePrefix: base
  destination:
    server: https://kubernetes.default.svc
    namespace: nginxns

