apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginxns
  labels:
    app: nginx
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: nginx
      namespace: nginxns
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
