apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-nginx-deployment
  template:
    metadata:
      labels:
        app: app-nginx-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
