apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    type: local
    namespace: nginxns
spec:
  storageClassName: manual
  claimRef:
    namespace: nginxns
    name: nginx-pvc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sounak/nginxstorage/"
